import { FormEvent, useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { api } from './lib/api';
import { supabase } from './lib/supabase';

type Row=Record<string,unknown>;type Workspace={companyId:string;companyName:string;role:string};
const tasks=['suggest_category','suggest_business_purpose','missing_context','summarize_exceptions','group_claims','draft_reviewer_reminder','summarize_finance_review'];
export function AgentPortal(){
  const[session,setSession]=useState<Session|null>(null);const[email,setEmail]=useState('');const[workspaces,setWorkspaces]=useState<Workspace[]>([]);const[workspace,setWorkspace]=useState<Workspace|null>(null);const[runs,setRuns]=useState<Row[]>([]);const[task,setTask]=useState(tasks[0]);const[entityType,setEntityType]=useState('claim');const[entityId,setEntityId]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{if(!session)return;supabase.from('company_memberships').select('company_id,role,companies(id,name)').eq('active',true).then(({data,error})=>{if(error)return setNotice(error.message);const list=(data??[]).map((row)=>{const c=row.companies as unknown as{name:string};return{companyId:String(row.company_id),companyName:c.name,role:String(row.role)};});setWorkspaces(list);setWorkspace(list[0]??null);});},[session?.user.id]);
  async function load(){if(!workspace)return;setRuns((await api<{runs:Row[]}>(`/v1/agent/runs?companyId=${workspace.companyId}`)).runs);}
  useEffect(()=>{load().catch((error)=>setNotice(error.message));},[workspace?.companyId]);
  async function signIn(event:FormEvent){event.preventDefault();const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${window.location.origin}/agent.html`}});setNotice(error?.message??'Check your email for the secure sign-in link.');}
  async function run(event:FormEvent){event.preventDefault();if(!workspace)return;setBusy(true);try{await api('/v1/agent/runs',{method:'POST',body:JSON.stringify({companyId:workspace.companyId,task,entityType,entityId:entityType==='company'?null:entityId})});setNotice('Advisory run completed. Review each proposal before accepting it.');await load();}catch(error){setNotice(error instanceof Error?error.message:'Advisor failed.');}finally{setBusy(false);}}
  async function confirm(proposalId:string,decision:'accept'|'reject'){await api(`/v1/agent/proposals/${proposalId}/confirm`,{method:'POST',body:JSON.stringify({decision,note:null})});setNotice(decision==='accept'?'Proposal acknowledged. No financial state was changed automatically.':'Proposal rejected and retained for evaluation.');await load();}
  if(!session)return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">Guardrailed assistance</p><h1>Spendsnap Advisor</h1><p>Evidence-grounded suggestions only. No approval, payment, tax eligibility, or evidence deletion.</p><form className="stack" onSubmit={signIn}><label>Work email<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></label><button className="primary">Send magic link</button></form>{notice&&<p>{notice}</p>}</section></main>;
  if(!workspace)return <main className="center"><p>No active workspace.</p></main>;
  return <div className="app-shell"><aside className="sidebar"><div><div className="brand"><span className="brand-mark">S</span><span><strong>Spendsnap Advisor</strong><small>Advisory only</small></span></div><label className="workspace-label">Workspace<select value={workspace.companyId} onChange={(e)=>setWorkspace(workspaces.find((w)=>w.companyId===e.target.value)??null)}>{workspaces.map((w)=><option key={w.companyId} value={w.companyId}>{w.companyName} · {w.role}</option>)}</select></label><nav><a href="/">Employee</a><a href="/finance.html">Finance</a></nav></div><button className="sign-out" onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><main className="main"><section className="page-section"><header className="page-header"><div><p className="eyebrow">Human-authorized AI</p><h2>Advisor runs</h2></div></header>{notice&&<div className="notice info">{notice}</div>}<div className="notice info">Advisor proposals are not approvals or accepted financial facts. Accepting records your decision but does not silently mutate the expense.</div><form className="form-grid" onSubmit={run}><label>Task<select value={task} onChange={(e)=>setTask(e.target.value)}>{tasks.map((item)=><option key={item}>{item}</option>)}</select></label><label>Entity type<select value={entityType} onChange={(e)=>setEntityType(e.target.value)}><option>receipt</option><option>claim</option><option>report</option><option>workflow</option><option>company</option></select></label>{entityType!=='company'&&<label>Entity ID<input value={entityId} onChange={(e)=>setEntityId(e.target.value)} required/></label>}<button className="primary" disabled={busy}>{busy?'Analyzing…':'Generate advice'}</button></form><div className="card-grid">{runs.map((run)=>{const proposals=(run.proposals as Row[]|undefined)??[];return <article className="data-card" key={String(run.id)}><div className="card-row"><strong>{String(run.task)}</strong><span className="status-pill">{String(run.status)}</span></div><p>Model: {String(run.model)} · prompt {String(run.prompt_version)}</p><code>{String(run.context_hash)}</code>{run.error_message&&<p className="notice error">{String(run.error_message)}</p>}{proposals.map((proposal)=><section key={String(proposal.id)}><h4>{String(proposal.title)}</h4><p>{String(proposal.rationale)}</p><p>Confidence: {String(proposal.confidence)} · risk: {String(proposal.risk_level)}</p><pre>{JSON.stringify(proposal.proposed_payload,null,2)}</pre><div className="action-row"><button className="primary" disabled={proposal.status!=='proposed'} onClick={()=>confirm(String(proposal.id),'accept')}>Accept as advice</button><button disabled={proposal.status!=='proposed'} onClick={()=>confirm(String(proposal.id),'reject')}>Reject</button><span className="status-pill">{String(proposal.status)}</span></div></section>)}</article>;})}</div></section></main></div>;
}
